### ISSUE TITLE
NorrisBot id Issue

### ISSUE THREAD

**Issue by algattos** [lmammino/norrisbot#14]
Hiya,

I've pulled down the latest master of the repo and got get the following issue:

TypeError: Cannot read property 'id' of undefined
    at Constructor.NorrisBot._isFromNorrisBot (/usr/local/lib/node_modules/norrisbot/lib/norrisbot.js:184:38)
    at Constructor.NorrisBot._onMessage (/usr/local/lib/node_modules/norrisbot/lib/norrisbot.js:61:15)
    at emitOne (events.js:96:13)
    at Constructor.emit (events.js:188:7)
    at Constructor.<anonymous> (/usr/local/lib/node_modules/norrisbot/node_modules/slackbots/index.js:62:18)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/usr/local/lib/node_modules/norrisbot/node_modules/ws/lib/WebSocket.js:841:10)
    at /usr/local/lib/node_modules/norrisbot/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/usr/local/lib/node_modules/norrisbot/node_modules/ws/lib/Receiver.js:371:5)

I've tried to get around it, but not having much luck. Your guide is awesome, I'm trying to modify it to basically build the foundations of some ChatOps I'm doing.

**Comment by lmammino** [comment]
Hi Guys, sorry for the very late reply. I just updated Norribot to version 2.0 using the official slack bot app and bots Node.js sdk. This version should be more stable and reliable. I won't be supporting anymore the old version, so I am closing this issue.

Feel free to open a new one if you have some issue with the new version.
