### ISSUE TITLE
Unexpected identifier with db

### ISSUE THREAD

**Issue by huasmc** [lmammino/norrisbot#18]
I've been trying to run the bot, I've followed the tutorial on Scotch.io, I tried copying the '.db' file in my '/data/' folder but also using the generator but I keep getting 'unexpected identifier:

```
/Users/huascar/Projects/cabify/slack_bot_practice/chuck_norris_bot/data/norrisbot.db:1
(function (exports, require, module, __filename, __dirname) { SQLite format 3
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

**Comment by lmammino** [comment]
Hello @HuascarMC, thanks for checking out this project!
Can you please tell me the exact command you are running?

**Comment by huasmc** [comment]
No problem, the tutorial is very well instructed.
The command I'm running is:
`BOT_API_KEY=your_api_key node bin/bot.js`

**Comment by devin5** [comment]
was this figured out ? Im going crazy with the exact same error

**Comment by TheDaekLord1989** [comment]
Is the isseue fixed? I have the same error.
