### ISSUE TITLE
Cannot read property 'id' of undefined, I am getting this error during run. Mac El Capitan. My Bot (not Chuck Norris) turns on but chuck norris doesn't reply on anything and it is shown offline

### ISSUE THREAD

**Issue by dsl10brc** [lmammino/norrisbot#6]
TypeError: Cannot read property 'id' of undefined
    at Constructor.NorrisBot._isFromNorrisBot (/Users/dlambor/norrisbot-master/lib/norrisbot.js:184:38)
    at Constructor.NorrisBot._onMessage (/Users/dlambor/norrisbot-master/lib/norrisbot.js:61:15)
    at emitOne (events.js:96:13)
    at Constructor.emit (events.js:188:7)
    at Constructor.<anonymous> (/Users/dlambor/norrisbot-master/node_modules/slackbots/index.js:59:18)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/dlambor/norrisbot-master/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/dlambor/norrisbot-master/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/dlambor/norrisbot-master/node_modules/ws/lib/Receiver.js:360:5)

**Comment by lmammino** [comment]
is the process up and running? where did you deployed it?

**Comment by thinkv** [comment]
Also receiving this error, seems to be the isFromNorrisBot method.

**Comment by fofiedelly** [comment]
Hi @dsl10brc , @thinkv  please make sure that your bot name is norrisbot or change at the line 22 of the norrisbot.js file and change "norrisbot" with your botname.
If the error is persisting i can try to hack and follow. It's working on my side.

**Comment by thinkv** [comment]
Thanks @fofiedelly , managed to work this out last night, didn't realise it had to match the slack bot name itself, after a bit of debugging worked it out :)

**Comment by lmammino** [comment]
Hi Guys, sorry for the very late reply. I just updated Norribot to version 2.0 using the official slack bot app and bots Node.js sdk. This version should be more stable and reliable. I won't be supporting anymore the old version, so I am closing this issue.

Feel free to open a new one if you have some issue with the new version.
